services:
    trigger_nginx:
        image: nginx
        container_name: soat-trigger-nginx
        ports:
            - 8002:80
        hostname: soat-trigger-nginx-hostname
        restart: on-failure:3
        volumes:
            - ./docker/containers/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./application:/var/www/html
        depends_on:
            trigger:
                condition: service_healthy
                restart: true

    trigger:
        container_name: soat-trigger
        hostname: soat-trigger-hostname
        build:
            context: .
            dockerfile: ./docker/images/php/Dockerfile
        volumes:
            - ./application:/var/www/html
        restart: on-failure:3
        expose:
            - "9000"
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "SCRIPT_NAME=/ping SCRIPT_FILENAME=/ping REQUEST_METHOD=GET cgi-fcgi -bind -connect 127.0.0.1:9000 | grep pong || exit 1",
                ]
            interval: 5s
            timeout: 3s
            retries: 3
        depends_on:
            trigger_pg:
                condition: service_healthy
                restart: true

    trigger_pg:
        image: postgres:17.5
        container_name: soat-trigger-pg
        restart: always
        ports:
            - 5434:5432
        env_file:
            - ./docker/containers/pg/env/.env.dev
        volumes:
            - trigger_pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 5s

volumes:
  trigger_pg_data:

networks:
    default:
        external: true
        name: soat-net
